=== VijayEluri/toolkit/imagestore/etc/images.dtd
<!--
<!DOCTYPE images PUBLIC "-//SPRING//DTD BEAN//EN"
 "http://www.trailmagic.com/dtd/images.dtd">
-->

<!ELEMENT images (roll+, image+)>
<!ELEMENT image (name, display-name, owner, caption?, copyright?, creator?,
                 number?, cd*, photo-data?, image-manifestation*)>

<!ELEMENT name (#PCDATA)>
<!ELEMENT display-name (#PCDATA)>
<!ELEMENT caption (#PCDATA)>
<!ELEMENT copyright (#PCDATA)>
<!ELEMENT creator (#PCDATA)>
<!ELEMENT number (#PCDATA)>

<!ELEMENT photo-data (roll-name, frame-number, notes?, capture-date?)>
<!ELEMENT roll-name (#PCDATA)>

<!ELEMENT image-manifestation (name, height?, width?, format?,
          original)>

<!ELEMENT notes (#PCDATA)>
<!ELEMENT capture-date (#PCDATA)>
<!ELEMENT roll (name, display-name, description, owner)>
<!ELEMENT description (#PCDATA)>


<!ELEMENT height (#PCDATA)>
<!ELEMENT width (#PCDATA)>
<!ELEMENT original (#PCDATA)>
<!ELEMENT format (#PCDATA)>
<!ELEMENT owner (#PCDATA)>
<!ELEMENT frame-number (#PCDATA)>
<!-- maybe this should be an attribute with #IMPLIED -->

<!ELEMENT cd (#PCDATA)>

=== VijayEluri/toolkit/modules/image/test/test-images.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE images PUBLIC "-//SPRING//DTD BEAN//EN"
 "http://www.trailmagic.com/dtd/images.dtd">

<!--
 Copyright (c) 2006 Oliver Stewart.  All Rights Reserved.

 This file is free software; you can redistribute it and/or modify
 it under the terms of the GNU General Public License as published by
 the Free Software Foundation; either version 2, or (at your option)
 any later version.

 This file is distributed in the hope that it will be useful,
 but WITHOUT ANY WARRANTY; without even the implied warranty of
 MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 GNU General Public License for more details.
-->

<images>
  <roll>
    <name>import-roll</name>
    <display-name>Import Roll</display-name>
    <description>A roll created for testing.</description>
    <owner>oliver</owner>
  </roll>
  <image>
    <name>oliver-suit-1</name>
    <display-name>Me in a suit</display-name>
    <caption>lookin' snazzy</caption>
    <copyright>Copyright 2004</copyright>
    <creator>Oliver Stewart</creator>
    <owner>oliver</owner>
    <photo-data>
      <notes></notes>
      <capture-date>2004-06-12</capture-date>
      <roll-name>vanity</roll-name>
      <frame-number>1</frame-number>
    </photo-data>
  </image>
</images>

=== VijayEluri/toolkit/imagestore/test/test-images.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE images PUBLIC "-//SPRING//DTD BEAN//EN"
 "http://www.trailmagic.com/dtd/images.dtd">

<images>
  <image>
    <name>oliver-suit-1</name>
    <display-name>Me in a suit</display-name>
    <caption>lookin' snazzy</caption>
    <copyright>Copyright 2004</copyright>
    <creator>Oliver Stewart</creator>
    <owner>oliver</owner>
    <photo-data>
      <notes></notes>
      <capture-date>2004-06-12</capture-date>
      <roll>vanity</roll>
    </photo-data>
  </image>
</images>

=== VijayEluri/toolkit/image/src/test/resources/test-images.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE images PUBLIC "-//SPRING//DTD BEAN//EN"
 "http://www.trailmagic.com/dtd/images.dtd">

<!--
 Copyright (c) 2006 Oliver Stewart.  All Rights Reserved.

 This file is free software; you can redistribute it and/or modify
 it under the terms of the GNU General Public License as published by
 the Free Software Foundation; either version 2, or (at your option)
 any later version.

 This file is distributed in the hope that it will be useful,
 but WITHOUT ANY WARRANTY; without even the implied warranty of
 MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 GNU General Public License for more details.
-->

<images>
  <roll>
    <name>import-roll</name>
    <display-name>Import Roll</display-name>
    <description>A roll created for testing.</description>
    <owner>oliver</owner>
  </roll>
  <image>
    <name>oliver-suit-1</name>
    <display-name>Me in a suit</display-name>
    <owner>oliver</owner>
    <caption>lookin' snazzy</caption>
    <copyright>Copyright 2004</copyright>
    <creator>Oliver Stewart</creator>
    <photo-data>
      <roll-name>vanity</roll-name>
      <frame-number>1</frame-number>
      <notes></notes>
      <capture-date>2004-06-12</capture-date>
    </photo-data>
  </image>
</images>
